An assorted collection of various improvements and refactors
FRC2706/2020-2706-Robot-Code pull request #84
Opened 2020-02-11 01:08 UTC by nrgill28

2020-02-11 20:21 UTC, kevlam2706 approved these changes
OK. I suggest that for cosmetic things, try to get the original authors to follow the standard that you are trying to set. (And obviously whenever you add code to the repo, make sure it's very easy to follow and emulate). People, particularly rookies, may feel bad if they perceive that their code is getting "fixed" by others.

2020-02-11 23:05 UTC, georgetzavelas reviewed
Any reason to remove the Xbox class?

2020-02-11 23:05 UTC, georgetzavelas commented on src/main/java/frc/robot/subsystems/DriveBase.java
> +    private static DriveBase INSTANCE = new DriveBase();
Can we revert this to the old Singleton Pattern? Or better yet this pattern: https://github.com/georgetzavelas/guava-examples/blob/master/src/com/design/pattern/creational/singleton/Singleton.java

2020-02-11 23:42 UTC, nrgill28 commented
The Xbox class was removed since it's a duplicate of a WPILib built-in.
Also, the DriveBase singleton pattern matches the one you've linked (The only difference I see is the lack of the `final` modifier)

2020-02-12 01:50 UTC, georgetzavelas commented
I see about the XBox class. The singleton pattern is different than the one I linked. It uses an inner static class not a static variable.

2020-02-13 00:01 UTC, nrgill28 commented
Oh. I don't know how I missed that...
I had updated the singleton pattern to be consistent with the rest of the subsystems in the code, should we switch to using this new one for all future singletons then?

2020-02-13 00:12 UTC, georgetzavelas commented
I would prefer us to use the inner static class way as it is thread safe. The only caveat with this approach is that initialization is for a failure state.

2020-02-15 15:08 UTC, nicojopr requested changes
Will need to rebase again and retest

2020-02-18 21:00 UTC, nrgill28 commented
This has become a little too outdated to merge easily. I'll just close this for now as it's not necessary.

2020-02-18 21:00 UTC, closed without merging